name: during
description: Money tracking application

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4
  get: ^4.6.3
  sqflite: ^2.0.2+1
  path: ^1.8.1
  flex_color_picker: ^2.5.0
  intl: ^0.17.0
  flutter_svg: ^1.0.3
  carousel_slider: ^4.1.1
  percent_indicator: ^4.2.2
  modal_bottom_sheet: ^2.0.1
  settings_ui: ^2.0.2
  get_storage: ^2.0.3
  qr_flutter: ^4.0.0
  url_launcher: ^6.1.2
  share_plus: ^4.0.4
  google_mobile_ads: ^1.2.0
  # cloud_firestore: ^3.1.10
  # firebase_core: ^1.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/category/
    - assets/saving/
    - assets/navigation/

  fonts:
    - family: NotoSans
      fonts:
        - asset: fonts/NotoSansJP-Regular.otf
