name: during
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.3.0
  sqflite: ^2.0.0+3
  path: ^1.8.0
  flex_color_picker: ^2.1.2
  intl: ^0.17.0
  flutter_svg: ^0.22.0
  carousel_slider: ^4.0.0
  percent_indicator: ^3.0.1
  modal_bottom_sheet: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/category/
    - assets/saving/
    - assets/navigation/

  fonts:
    - family: NotoSans
      fonts:
        - asset: fonts/NotoSansJP-Regular.otf
