const Map<String, String> idID = {
  'home': 'Beranda',
  'transaction': 'Transaksi',
  'saving': 'Simpanan',
  'setting': 'Pengaturan',
  'income': 'Pemasukan',
  'expense': 'Pengeluaran',
  'see_all': 'Lihat Semua',
  'recent_transaction': 'Transaksi Terakhir',
  'empty_transaction': 'Transaksi Kosong',
  'sharing': 'Sharing',
  'filter': 'Filter',
  'range': '',
  'type': 'Tipe',
  'category': 'Kagori',
  'daily': 'Harian',
  'weekly': 'Mingguan',
  'monthly': 'Bulanan',
  'education': 'Pendidikan',
  'food': 'Makanan',
  'grocery': 'Belanjaan',
  'health': 'Kesehatan',
  'subscription': 'Subscription',
  'transportation': 'Transportasi',
  'home_menu': 'Rumah',
  'travel': 'Travel',
  'other': 'Lainnya',
  'fee': 'Gaji',
  'bonus': 'Bonus',
  'selling': 'Penjualan',
  'empty_saving': 'Simpanan Kosong',
  'total': 'Total',
  'name': 'Nama',
  'date': 'Tanggal',
  'time': 'Waktu',
  'income_category': 'Kategori Pemasukan',
  'expense_category': 'Kategori Pengeluaran',
  'rating': 'Rating',
  'share': 'Bagikan',
  'language': 'Bahasan',
  'google_backup': 'Google Drive Backup',
  'dark_theme': 'Tema Gelap',
  'hide_saving': 'Sembunyikan Simpanan',
  'hide_saving_desc': 'Sembunyikan kartu simpanan di halaman depan',
  'common': 'Umum',
  'from': 'Dari',
  'created': 'Dibuat',
  'delete_transaction_title': 'Hapus Transaksi',
  'delete_transaction_message': 'Apa anda yakin akan menghapus transaksi ini?',
  'cancel': 'Batal',
  'ok': 'OK',
  'delete_saving_title': 'Hapus Simpanan',
  'delete_saving_message': 'Apa anda yakin akan menghapus simpanan ini?',
};

const Map<String, String> enUS = {
  'home': 'Home',
  'transaction': 'Transaction',
  'saving': 'Saving',
  'setting': 'Setting',
  'income': 'Income',
  'expense': 'Expense',
  'see_all': 'See All',
  'recent_transaction': 'Recent Transaction',
  'empty_transaction': 'Empty Transaction',
  'sharing': 'Sharing',
  'filter': 'Filter',
  'range': 'Range',
  'type': 'Type',
  'category': 'Category',
  'daily': 'Daily',
  'weekly': 'Weekly',
  'monthly': 'Monthly',
  'education': 'Education',
  'food': 'Food',
  'grocery': 'Grocery',
  'health': 'Health',
  'subscription': 'Subcription',
  'transportation': 'Transportation',
  'home_menu': 'Home',
  'travel': 'Travel',
  'other': 'Other',
  'fee': 'Fee',
  'bonus': 'Bonus',
  'selling': 'Selling',
  'empty_saving': 'Empty Saving',
  'total': 'Total',
  'name': 'Name',
  'date': 'Date',
  'time': 'Time',
  'income_category': 'Income Category',
  'expense_category': 'Expense Category',
  'rating': 'Rating',
  'share': 'Share',
  'language': 'Language',
  'google_backup': 'Google Drive Backup',
  'dark_theme': 'Dark Theme',
  'hide_saving': 'Hide Saving',
  'hide_saving_desc': 'Hide saving slider in home page',
  'common': 'Common',
  'from': 'From',
  'created': 'Created',
  'delete_transaction_title': 'Delete Transaction',
  'delete_transaction_message': 'Are you sure want to delete transaction?',
  'cancel': 'Cancel',
  'ok': 'OK',
  'delete_saving_title': 'Delete Saving',
  'delete_saving_message': 'Are you sure want to delete saving?',
};
