const Map<String, String> idID = {
  'home': 'Beranda',
  'transaction': 'Transaksi',
  'saving': 'Simpanan',
  'setting': 'Pengaturan',
  'income': 'Pemasukan',
  'expense': 'Pengeluaran',
  'see_all': 'Lihat Semua',
  'recent_transaction': 'Transaksi Harian',
  'empty_transaction': 'Transaksi Kosong',
  'sharing': 'Sharing',
  'filter': 'Filter',
  'range': '',
  'type': 'Tipe',
  'category': 'Kategori',
  'daily': 'Harian',
  'weekly': 'Mingguan',
  'monthly': 'Bulanan',
  'education': 'Pendidikan',
  'food': 'Makanan',
  'grocery': 'Belanjaan',
  'health': 'Kesehatan',
  'subscription': 'Subscription',
  'transportation': 'Transportasi',
  'home_menu': 'Rumah',
  'travel': 'Travel',
  'other': 'Lainnya',
  'fee': 'Gaji',
  'bonus': 'Bonus',
  'selling': 'Penjualan',
  'empty_saving': 'Simpanan Kosong',
  'total': 'Total',
  'name': 'Nama',
  'date': 'Tanggal',
  'time': 'Waktu',
  'income_category': 'Kategori Pemasukan',
  'expense_category': 'Kategori Pengeluaran',
  'rating': 'Rating',
  'share': 'Bagikan',
  'language': 'Bahasa',
  'dark_theme': 'Mode Gelap',
  'hide_saving': 'Sembunyikan Simpanan',
  'hide_saving_desc': 'Sembunyikan kartu simpanan di halaman depan',
  'common': 'Umum',
  'from': 'Dari',
  'to': 'Ke',
  'created': 'Dibuat',
  'delete_transaction_title': 'Hapus Transaksi',
  'delete_transaction_message': 'Apa anda yakin akan menghapus transaksi ini?',
  'cancel': 'Batal',
  'ok': 'OK',
  'delete_saving_title': 'Hapus Simpanan',
  'delete_saving_message': 'Transaksi dengan simpanan ini juga akan dihapus?',
  'saving_category': 'Kategori Penyimpanan',
  'bank': 'Bank',
  'emoney': 'E-Money',
  'cash': 'Tunai',
  'balance': 'Saldo',
  'color': 'Warna',
  'insert': 'Masukkan',
  'detail_transaction': 'Detil Transaction',
  'select_color': 'Pilih warna',
  'select_shade': 'Pilih warna bayang',
  'choose_saving': 'Pilih Penyimpanan',
  'share_payment': 'Bagi Pembayaran',
  'total_amount': 'Total Harga',
  'create_payment': 'Buat Pembayaran',
  'delete': 'Hapus',
  'category_empty': 'Kategori Kosong',
  'category_icon': 'Ikon Kategori',
  'delete_category_title': 'Hapus kategori ini?',
  'delete_category_message':
      'Semua transaksi dalam kategori akan ikut terhapus',
  'create': 'Buat',
  'daily_income': 'Pemasukkan Harian',
  'daily_expense': 'Pengeluaran Harian',
  'delete_data': 'Hapus Data',
  'delete_data_message': 'Apakah kamu yakin akan menghapus semua data?',
  'custom': 'Custom',
  'end': 'Akhir',
  'start': 'Awal',
  'reset': 'Reset',
  'delete_transfer_message': 'Apa anda yakin akan menghapus transfer ini?',
  'transfer': 'Transfer',
  'admin_fee': 'Biaya Admin',
  'statistic': 'Statistik',
  'account': 'Akun',
  'management': 'Pengelolaan',
  'budget': 'Anggaran',
  'password': 'Kata Sandi',
  'backup': 'Cadangkan'
};

const Map<String, String> enUS = {
  'home': 'Home',
  'transaction': 'Transaction',
  'saving': 'Saving',
  'setting': 'Setting',
  'income': 'Income',
  'expense': 'Expense',
  'see_all': 'See All',
  'recent_transaction': 'Daily Transaction',
  'empty_transaction': 'Empty Transaction',
  'sharing': 'Sharing',
  'filter': 'Filter',
  'range': 'Range',
  'type': 'Type',
  'category': 'Category',
  'daily': 'Daily',
  'weekly': 'Weekly',
  'monthly': 'Monthly',
  'education': 'Education',
  'food': 'Food',
  'grocery': 'Grocery',
  'health': 'Health',
  'subscription': 'Subcription',
  'transportation': 'Transportation',
  'home_menu': 'Home',
  'travel': 'Travel',
  'other': 'Other',
  'fee': 'Fee',
  'bonus': 'Bonus',
  'selling': 'Selling',
  'empty_saving': 'Empty Saving',
  'total': 'Total',
  'name': 'Name',
  'date': 'Date',
  'time': 'Time',
  'income_category': 'Income Category',
  'expense_category': 'Expense Category',
  'rating': 'Rating',
  'share': 'Share',
  'language': 'Language',
  'dark_theme': 'Dark Mode',
  'hide_saving': 'Hide Saving',
  'hide_saving_desc': 'Hide saving slider in home page',
  'common': 'Common',
  'from': 'From',
  'to': 'To',
  'created': 'Created',
  'delete_transaction_title': 'Delete Transaction',
  'delete_transaction_message': 'Are you sure want to delete transaction?',
  'cancel': 'Cancel',
  'ok': 'OK',
  'delete_saving_title': 'Delete Saving',
  'delete_saving_message': 'Transaction with this saving will also be deleted?',
  'saving_category': 'Saving Category',
  'bank': 'Bank',
  'emoney': 'E-Money',
  'cash': 'Cash',
  'balance': 'Balance',
  'color': 'Color',
  'insert': 'Insert',
  'detail_transaction': 'Transaction Detail',
  'select_color': 'Select color',
  'select_shade': 'Select color chade',
  'choose_saving': 'Choose Saving',
  'share_payment': 'Share Payment',
  'total_amount': 'Total Amount',
  'create_payment': 'Create Payment',
  'delete': 'Delete',
  'category_empty': 'Category is Empty',
  'category_icon': 'Category Icons',
  'delete_category_title': 'Delete this category?',
  'delete_category_message':
      'All transactions in this category will also be deleted',
  'create': 'Create',
  'daily_income': 'Daily Income',
  'daily_expense': 'Daily Expense',
  'delete_data': 'Delete Data',
  'delete_data_message': 'All data will be deleted, are you sure?',
  'custom': 'Custom',
  'end': 'End',
  'start': 'Start',
  'reset': 'Reset',
  'delete_transfer_message': 'Are you sure wanto to delete transfer?',
  'transfer': 'Transfer',
  'admin_fee': 'Admin Fee',
  'statistic': 'Statistic',
  'account': 'Account',
  'management': 'Management',
  'budget': 'Budget',
  'password': 'Password',
  'backup': 'Backup',
};
